version: '3'

services:
  app:
    build: .
    container_name: alumnitos
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # Montar la carpeta local en el contenedor
    environment:
      - NODE_ENV=production
